In [5]:
# 웹 스크래핑
import requests
from bs4 import BeautifulSoup

# kbo 팀순위 사이트
url = "https://www.koreabaseball.com/record/teamrank/teamrankdaily.aspx"
response = requests.get(url)
# response.text
# html 파싱
html = BeautifulSoup(response.text, 'html.parser')

# select() 사용 검색
# 첫번째 테이블 - select_one()
first_table = html.select_one('table.tData > tbody')
# print(first_table)

# 특정 열 선택(여러개 - td:nth-of-type(1)) - select()
순위 = first_table.select('tr > td:nth-of-type(1)')
# 순위
# for i in 순위:
#    print(i.text)
# 순위 리스트 만들기
[int(i.text) for i in 순위]

팀 = first_table.select('tr > td:nth-of-type(2)')
[i.text for i in 팀]

승 = first_table.select('tr > td:nth-of-type(4)')
[int(i.text) for i in 승]

패 = first_table.select('tr > td:nth-of-type(5)')
[int(i.text) for i in 패]

무 = first_table.select('tr > td:nth-of-type(6)')
[int(i.text) for i in 무]

승률 = first_table.select('tr > td:nth-of-type(7)')
[float(i.text) for i in 승률]

[0.621, 0.557, 0.545, 0.529, 0.511, 0.506, 0.5, 0.494, 0.43, 0.307]

In [15]:
# 텍스트 파일 쓰기
with open("datas/kbo_2025.txt", "w") as f:
    f.write("===== 2025 한국 프로야구 팀순위 =====\n")
    head = "순위\t팀\t승\t패\t무\t승률"
    f.write(head)
    f.write('\n')
    for i in range(len(팀)): #10번 반복
        txt = f'{순위[i].text}\t{팀[i].text}\t{승[i].text}\t{패[i].text}\t \
{무[i].text}\t{승률[i].text}\n'
        f.write(txt)

In [6]:
with open("datas/kbo_2025.txt", "r") as f:
    data = f.read()
    print(data)

===== 2025 한국 프로야구 팀순위 =====
순위	팀	승	패	무	승률
1	한화	54	33	 2	0.621
2	LG	49	39	 2	0.557
3	롯데	48	40	 3	0.545
4	KIA	45	40	 3	0.529
5	KT	45	43	 3	0.511
6	SSG	43	42	 3	0.506
7	NC	40	40	 5	0.500
8	삼성	43	44	 1	0.494
9	두산	37	49	 3	0.430
10	키움	27	61	 3	0.307

In [10]:
# CSV 파일로 생성

import pandas as pd

# 데이터프레임 생성
data = {
    "순위": [int(i.text) for i in 순위],
    "팀": [i.text for i in 팀],
    "승": [int(i.text) for i in 승],
    "패": [int(i.text) for i in 패],
    "무": [int(i.text) for i in 무],
    "승률": [float(i.text) for i in 승률]
}

df = pd.DataFrame(data)

# csv파일로 변환(index는 제외)
df.to_csv("./datas/kbo_2025.csv", index = False)

# csv 파일 읽기
kbo = pd.read_csv("./datas/kbo_2025.csv")
kbo

   순위    팀   승   패  무     승률
0   1   한화  54  33  2  0.621
1   2   LG  49  39  2  0.557
2   3   롯데  48  40  3  0.545
3   4  KIA  45  40  3  0.529
4   5   KT  45  43  3  0.511
5   6  SSG  43  42  3  0.506
6   7   NC  40  40  5  0.500
7   8   삼성  43  44  1  0.494
8   9   두산  37  49  3  0.430
9  10   키움  27  61  3  0.307